[test]
# Test timeout settings
timeout = 5000

# Test environment
environment = "node"

# Test file patterns to include (only TypeScript test files in src)
include = ["src/**/*.test.ts"]

# Explicitly exclude compiled files and other directories
exclude = [
  "dist/**",
  "node_modules/**",
  "coverage/**",
  "examples/**",
  "**/*.js",
  "**/*.d.ts",
  "**/*.config.*",
  "**/mcp-server.integration.test.ts"
]